# Generated by Django 6.0.4 on 2026-04-27 02:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('f', 'FUN_FACT'), ('t', 'HEALTH_TIP')], max_length=1)),
                ('text_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_lang', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewStockAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_triggered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('sku_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('n', 'neutral')], default='n', max_length=1)),
                ('category', models.CharField(choices=[('cor', 'corporate'), ('can', 'canvas'), ('des', 'designers'), ('san', 'sandals'), ('bts', 'boots')], default='can', max_length=3)),
                ('size', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('avl', 'available'), ('sld', 'sold')], default='avl', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoes/')),
                ('is_ghost_entry', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('o', 'owing'), ('p', 'paid')], max_length=1)),
                ('date_ordered', models.DateField(default=django.utils.timezone.now)),
                ('order_expiration_date', models.DateField(blank=True, null=True)),
                ('is_picked_up', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Business Dashboard',
                'verbose_name_plural': 'Business Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shoe',),
        ),
        migrations.CreateModel(
            name='ShoeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_size', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
    ]
