# Generated by Django 6.0.4 on 2026-04-29 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_salesummary_remove_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoerequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shoe'),
        ),
    ]
