# Generated by Django 6.0.4 on 2026-05-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoerequest_fulfilled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('o', 'owing'), ('p', 'paid')], default='owing', max_length=10),
        ),
    ]
