# Generated by Django 6.0.4 on 2026-05-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('o', 'owing'), ('p', 'paid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('cor', 'corporate'), ('can', 'canvas'), ('des', 'designers'), ('san', 'sandals'), ('bts', 'boots')], default='can', max_length=4),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='status',
            field=models.CharField(choices=[('avl', 'available'), ('sold', 'sold')], default='avl', max_length=20),
        ),
    ]
