# Generated by Django 6.0.4 on 2026-05-05 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shoe_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoerequest',
            name='is_fulfilled',
        ),
    ]
